import type { Metadata } from "next";

import "./globals.css";
import { inter } from "@/config/fonts";

import { Providers } from "./providers";
import { Footer, NavBar } from "@/components";

export const metadata: Metadata = {
  title: "ImDamianDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
